server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - '*'
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/project/**
          filters:
            - AuthenticationFilter
        - id: workItem-service
          uri: lb://workItem-service
          predicates:
            - Path=/workItem/**
          filters:
            - AuthenticationFilter

  ## zipkin configuration

  zipkin:
    baseUrl: http://localhost:9411
management:
  tracing:
    sampling:
      probability: 1.0
