spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: pedalplanetbicycles@gmail.com
    password: lwuouxyjayzvvkcn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8083

  ## zipkin configuration

  zipkin:
    baseUrl: http://localhost:9411
management:
  tracing:
    sampling:
      probability: 1.0
