server:
  port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3309/plan_b_workItem
    username: root
    password: password#2#2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: workItem-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  ## zipkin configuration
  zipkin:
    baseUrl: http://localhost:9411

  #kafka configuration
  kafka:
    producer:
      bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
management:
  tracing:
    sampling:
      probability: 1.0
