spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ajithkrkd/config-server_plan-b.git
      enabled: true

  application:
    name: config-server
server:
  port: 8888